import type { CarriedItem } from "@/types/build";

export const CARRIED_ITEMS: CarriedItem[] = [
  {
    id: "ferocious-fang-legendary",
    nome: "Ferocious Fang",
    slug: "ferocious-fang",
    raridade: "Legendary",
    cp: 200,
    bonusBase: "Damage Amp +10%",
    efeitoCore: "O Aniimo equipado recebe +0,8 ATK para cada nível do próprio Aniimo.",
    escalaPorNivel: { atributo: "ataque", rotulo: "ATK", valor: 0.8 },
    melhoria10: { descricao: "ATK +2", atributo: "ataque", rotulo: "ATK", valor: 2 },
    melhoria20: "Damage Amp +10%; o efeito pode ser ampliado quando a condição de ATK/Potencial indicada pelo jogo é atendida.",
    fonte: {
      tipo: "DADOS_DO_JOGO_VIA_COMUNIDADE",
      url: "https://aniidex.com/aniimo/irisal/",
      verificadoEm: "2026-09-12",
    },
  },
  {
    id: "spirited-feather-legendary",
    nome: "Spirited Feather",
    slug: "spirited-feather",
    raridade: "Legendary",
    cp: 200,
    bonusBase: "REGEN +10%",
    efeitoCore: "O Aniimo equipado recebe +0,8 REGEN para cada nível do próprio Aniimo.",
    escalaPorNivel: { atributo: "regen", rotulo: "REGEN", valor: 0.8 },
    melhoria10: { descricao: "REGEN +2", atributo: "regen", rotulo: "REGEN", valor: 2 },
    melhoria20: "Redução de recarga +10%; o efeito pode ser ampliado quando a condição de REGEN indicada pelo jogo é atendida.",
    fonte: {
      tipo: "DADOS_DO_JOGO_VIA_COMUNIDADE",
      url: "https://aniidex.com/aniimo/skippy/",
      verificadoEm: "2026-09-12",
    },
  },
  {
    id: "gargantuan-claw-legendary",
    nome: "Gargantuan Claw",
    slug: "gargantuan-claw",
    raridade: "Legendary",
    cp: 200,
    bonusBase: "BREAK +10%",
    efeitoCore: "O Aniimo equipado recebe +0,8 BREAK para cada nível do próprio Aniimo.",
    escalaPorNivel: { atributo: "break", rotulo: "BREAK", valor: 0.8 },
    melhoria10: { descricao: "BREAK +2", atributo: "break", rotulo: "BREAK", valor: 2 },
    melhoria20: "BREAK +10%; o efeito pode ser dobrado quando a condição de Potencial de BREAK indicada pelo jogo é atendida.",
    fonte: {
      tipo: "DADOS_DO_JOGO_VIA_COMUNIDADE",
      url: "https://www.aniimoverse.com/items/gargantuan-claw",
      verificadoEm: "2026-09-12",
    },
  },
  {
    id: "auspicious-bell-legendary",
    nome: "Auspicious Bell",
    slug: "auspicious-bell",
    raridade: "Legendary",
    cp: 200,
    bonusBase: "REGEN +10%",
    efeitoCore: "Ao usar uma habilidade, há 20% de chance de ganhar 5 EP.",
    melhoria10: {
      descricao: "Após 5 usos consecutivos sem ativar o efeito, a próxima habilidade tem 100% de chance de ativá-lo.",
    },
    melhoria20: "Quando o efeito de REGEN de um Core Bonus ativa, ganha 5 EP extras e concede 1 acúmulo de Luck ao time.",
    fonte: {
      tipo: "DADOS_DO_JOGO_VIA_COMUNIDADE",
      url: "https://aniidex.com/items/auspicious-bell/?id=551016",
      verificadoEm: "2026-09-12",
    },
  },
  {
    id: "miraculous-fleece-legendary",
    nome: "Miraculous Fleece",
    slug: "miraculous-fleece",
    raridade: "Legendary",
    cp: 200,
    bonusBase: "Enhanced Healing Effect +10%",
    efeitoCore: "Transfere 30% da cura excedente do alvo para o Aniimo com a menor porcentagem de HP.",
    melhoria10: { descricao: "Aumenta a cura em 10%." },
    melhoria20: "A transferência de cura excedente aumenta para 60%.",
    fonte: {
      tipo: "DADOS_DO_JOGO_VIA_COMUNIDADE",
      url: "https://aniidex.com/aniimo/skippy/",
      verificadoEm: "2026-09-12",
    },
  },
  {
    id: "capacitous-battery-legendary",
    nome: "Capacitous Battery",
    slug: "capacitous-battery",
    raridade: "Legendary",
    cp: 200,
    bonusBase: "Damage Amp +10%",
    efeitoCore: "Aumenta o dano da Ultimate em 30%.",
    melhoria10: { descricao: "Após usar uma Ultimate, reembolsa imediatamente 10% dos Ultimate Points." },
    melhoria20: "Após usar uma Ultimate, aumenta em 30% a eficiência de ganho de Ultimate Points por 10 s.",
    fonte: {
      tipo: "DADOS_DO_JOGO_VIA_COMUNIDADE",
      url: "https://www.aniimoverse.com/items/capacitous-battery",
      verificadoEm: "2026-09-12",
    },
  },
  {
    id: "explosive-gloves-legendary",
    nome: "Explosive Gloves",
    slug: "explosive-gloves",
    raridade: "Legendary",
    cp: 200,
    bonusBase: "Damage Amp +10%",
    efeitoCore: "Aumenta o dano causado em 5% para cada 10 EP disponíveis no momento.",
    melhoria10: { descricao: "O bônus por cada 10 EP sobe para 7,5%." },
    melhoria20: "Concede 10% de chance de não consumir EP ao lançar uma habilidade.",
    fonte: {
      tipo: "DADOS_DO_JOGO_VIA_COMUNIDADE",
      url: "https://aniidex.com/aniimo/scorchhowl/",
      verificadoEm: "2026-09-12",
    },
  },
];
